### ISSUE TITLE
Is it possible to use this in conjuction with vim-asterisk?

### ISSUE THREAD

**Issue by alerque** [Konfekt/vim-select-replace#2]
It seems either I have some mental block on how to configure it properly  or this plugin  does not play nicely with also using haya14busa/vim-asterisk. Is there a way to configure this so they actually play nicely together? Since it uses a bunch of the same  code anyway and vim-asterisk doesn't define any keybindings by default might it not be better to make that a dependency of this?

**Comment by Konfekt** [comment]
As this plug-in only defines operator-mode mappings, it should be possible by using
```vim
xmap *   <Plug>(asterisk-*)
xmap #   <Plug>(asterisk-#)
xmap g*  <Plug>(asterisk-g*)
xmap g#  <Plug>(asterisk-g#)

nmap *   <Plug>(asterisk-*)
nmap #   <Plug>(asterisk-#)
nmap g*  <Plug>(asterisk-g*)
nmap g#  <Plug>(asterisk-g#)
```
instead of
```vim
map *   <Plug>(asterisk-*)
map #   <Plug>(asterisk-#)
map g*  <Plug>(asterisk-g*)
map g#  <Plug>(asterisk-g#)
```

I prefer not to make it a dependency as vim-asterisk does more than this plug-in (mere `omaps`). Vim lacks a function to get the visual selection, and the one there is supersolid. A shorter variant is offered at https://github.com/vim-jp/vital.vim/blob/12e7ce41b5a353d6fb6dcda66e49988d7cae36a5/autoload/vital/__vital__/Vim/Buffer.vim#L75

**Comment by alerque** [comment]
Yes, that does clear up the conflict. It might be worth documenting this as `vim-asterisk` is likely to be a common overlap with users attracted to this.
